### PR TITLE
Update ddf-py3.singularity

### PR DESCRIPTION
**Pull request by AlexKurek**
extended LD_LIBRARY_PATH
fixed Dysco install
removed unnecessary subversion package
few more minor cleanups

### CODE REVIEW

**Comment by AlexKurek** [comment]
Please consider also some minor changes posted here. They may be helpful later.

**Comment by mhardcastle** [comment]
Thanks. Please don't modify this to remove packages that might be useful to me in sandbox mode until the development is finished though! There's a reason why I have emacs and htop in there.

Is there a reason why you want to purge cmake and git other than the size of the resulting binary?

Note again that at the moment this does not give a working pipeline -- I am working on fixes to killMS and the pipeline itself.

**Comment by AlexKurek** [comment]
> Is there a reason why you want to purge cmake and git other than the size of the resulting binary?

No, no other reason. It just seems those packages are the safest to remove

**Comment by mhardcastle** [comment]
OK, let's leave all such tidying up till the image is fully working. Merging...

**Pull request merged**
