### PR TITLE
Stokesv fix

### PR DESCRIPTION
**Pull request by twshimwell**
Pull request to a) image each observation in stokes V instead of all together; b) make splitisland size optional; c) make using maskdiffuse optional.

Not fully tested yet...

### CODE REVIEW

**Comment by mhardcastle** [comment]
Have you thought about integration with the uploads/archive for the QUV stuff, Tim?

**Comment by mhardcastle** [comment]
This needs a test pipeline run before we merge it.

**Comment by twshimwell** [comment]
@mhardcastle I finally got around to testing this. Pushed one small typo yesterday but otherwise seems to work as expected. So produces V maps for each epoch, named e.g.:

image_full_high_stokesV_L796616.dirty.fits

**Comment by mhardcastle** [comment]
OK cool. I will merge, make a new singularity and we'll see if it works in production.

**Comment by twshimwell** [comment]
Thank you very much!

**Pull request merged**
