### PR TITLE
Dynamic spectra

### PR DESCRIPTION
**Pull request by cyriltasse**
OK - added a `DynSpecMS` run by default. It download the source list from an ftp in leiden and if targets are present withing the field, does produce dynamic spectrum and saves the results in `DynSpecs_<OBSID>`. Tested and working.

So there is an additional requirement on https://github.com/cyriltasse/DynSpecMS

### CODE REVIEW

**Comment by mhardcastle** [comment]
Cool!

My only question is why it forces the second selfcal?

**Comment by twshimwell** [comment]
sneaky

**Comment by cyriltasse** [comment]
It doesn't force the second selfcal actually... where do you see that?

**Comment by mhardcastle** [comment]
Sorry, I wasn't reading carefully enough (trying to multitask with the telecon). Your last commit removes part of the confusion.

I think we can merge this.

**Comment by cyriltasse** [comment]
We'll work a bit more on it. Before pushing the button again and reducing again - I'll remind you to pull again on DynSpecMS...

**Pull request merged**
