### PR TITLE
Update sub-sources-outside-region.py

### PR DESCRIPTION
**Pull request by rvweeren**
Major update. 
-Added functionality to run LBA pipeline extracts
-Make script Python2 and Python 3 compatible 
-Updated box handling to rotate them to the local north (important for an extract that uses multiple pointings)
-Added extract argument options for user-specified inputs for non-default extracts

### CODE REVIEW

**Comment by rvweeren** [comment]
BTW added some helper function back  into the script otherwise I cannot run it in the LBA singularity image from Francesco (which does not included the ddf-pipeline at the moment)

**Comment by rvweeren** [comment]
Not sure what the "numberstrings is used to avoid boost issues" is about. I hope this is already addressed(?) On our Leiden I've not seen these issues.

**Comment by mhardcastle** [comment]
OK to add the helper functions back I guess. Just means that they may get out of step with the master ones -- I think that caused me some confusion when I was working with this code for the VLOW work.

The numberstrings code was added by @twshimwell , maybe he wants to comment on whether it's still needed? Then I can merge.

**Comment by twshimwell** [comment]
Hmmm yes I suspect numberstrings is no longer needed.

**Pull request merged**
